#!/usr/bin/env python3
"""一键脚本：编译 app.bin → Renode 运行 RTOS+App 双分区场景 → 自动验证摘要。

全量模式镜像 joc-base/tools/renode/stm32f407_jos_app.resc 的流程：
  启动 → sleep 2 → 发 console 命令(PING/TICKS/ECHO) → sleep 30 →
  再发一次 console 命令 → sleep 30 → quit（验证中途无 stall）。

用法：
  python build_run_renode.py               # 构建 + 全量运行 (~70s)
  python build_run_renode.py --quick       # 构建 + 快速验证 (~30s wall)
  python build_run_renode.py --seconds 20  # 自定义运行秒数（发一次 console 命令后）
  python build_run_renode.py --no-build    # 跳过构建，直接用现有 app.bin
  python build_run_renode.py --keep-resc   # 保留生成的临时 resc 供调试
  python build_run_renode.py --mips 168    # 贴近真实 168MHz 的时序保真度

退出码：0 = 构建 + 运行 + 验证全部通过；1 = 任一环节失败。

依赖（路径按本机环境，改顶部常量或传 CLI 参数）：
  - Renode:      D:/soft/Renode/renode.exe
  - 系统镜像:     ../joc-base/build_rel/stm32f407_minimal.elf（joc-base build_rel.bat 产出）
  - 平台脚本:     ../joc-base/tools/renode/（stm32f4_jos.repl / uart_capture.py / send_cmd.py）
  - 构建:        本工程 build_app.py（cargo + app.ld 链接 + objcopy）
"""
import argparse
import os
import re
import subprocess
import sys
import time

BASE = os.path.dirname(os.path.abspath(__file__))

# ---- 路径配置（按需修改，风格与 flash.py 一致）----
RENODE_DIR  = r"D:\soft\Renode"                                  # renode.exe 所在目录
RENODE_TOOLS = os.path.join(BASE, "..", "joc-base", "tools", "renode")  # repl / hook 脚本
SYS_ELF     = os.path.join(BASE, "..", "joc-base", "build_rel", "stm32f407_minimal.elf")
APP_BIN     = os.path.join(BASE, "app.bin")
APP_ADDR    = "0x08060000"

LOG_PATH    = os.path.join(BASE, "renode_app.log")   # Renode 全量输出
TMP_RESC    = os.path.join(BASE, "_renode_app_tmp.resc")  # 生成的临时 resc（运行后删除）


def win_path(p):
    """路径统一成 Renode 可识别的 Windows 盘符形式（D:/...）。

    兼容 MSYS/Git-Bash 风格 Python（os.path.abspath 返回 /d/...）：
    先转正斜杠，再把前导 /x/ 归一为 X:/，避免 Renode 找不到文件。
    """
    p = os.path.abspath(p).replace("\\", "/")
    if p.startswith("/") and len(p) > 2 and p[2] == "/":
        p = p[1].upper() + ":" + p[2:]
    return p


def check_env():
    """前置检查：renode / 系统镜像 / 平台脚本 是否存在。"""
    renode = os.path.join(RENODE_DIR, "renode.exe")
    if not os.path.exists(renode):
        print(f"[ERR] 未找到 Renode: {renode}（改脚本顶部 RENODE_DIR）", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(SYS_ELF):
        print(f"[ERR] 缺系统镜像: {SYS_ELF}", file=sys.stderr)
        print("      请先在 joc-base 执行 build_rel.bat（RTOS_SELFTEST=OFF 发布版）", file=sys.stderr)
        sys.exit(1)
    for name in ("stm32f4_jos.repl", "uart_capture.py", "send_cmd.py"):
        if not os.path.exists(os.path.join(RENODE_TOOLS, name)):
            print(f"[ERR] 缺 Renode 平台脚本: {RENODE_TOOLS}\\{name}", file=sys.stderr)
            sys.exit(1)


def build_app():
    """调 build_app.py：cargo build → app.ld 链接 → objcopy 出 app.bin。"""
    print("[1/2] 构建 app.bin ...")
    r = subprocess.run([sys.executable, "build_app.py"], cwd=BASE)
    if r.returncode != 0:
        print("[ERR] build_app.py 构建失败", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(APP_BIN):
        print(f"[ERR] 未找到构建产物: {APP_BIN}", file=sys.stderr)
        sys.exit(1)


def make_resc(mips, full, run_seconds):
    """生成临时 resc：镜像 stm32f407_jos_app.resc（可缩短运行时长）。"""
    repl = win_path(os.path.join(RENODE_TOOLS, "stm32f4_jos.repl"))
    cap  = win_path(os.path.join(RENODE_TOOLS, "uart_capture.py"))
    send = win_path(os.path.join(RENODE_TOOLS, "send_cmd.py"))
    elf  = win_path(SYS_ELF)
    app  = win_path(APP_BIN)
    lines = [
        "# generated by build_run_renode.py (mirror of joc-base stm32f407_jos_app.resc)",
        "mach create",
        f"machine LoadPlatformDescription @{repl}",
        f"include @{cap}",
        f"sysbus LoadELF @{elf}",
        f"sysbus LoadBinary @{app} {APP_ADDR}",
        f"cpu PerformanceInMips {mips}",
        "start",
        "sleep 2",
        f"include @{send}",
    ]
    if full:
        # 全量：与 joc-base 官方 resc 一致，两轮 console 探测证明中途无 stall
        lines += ["sleep 30", f"include @{send}", "sleep 30"]
    else:
        lines += [f"sleep {run_seconds}"]
    lines += ["quit"]
    with open(TMP_RESC, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return "full" if full else "custom"


def run_renode(mips, total_virtual):
    """启动 Renode（headless），输出重定向到 LOG_PATH。"""
    print(f"[2/2] Renode 运行中（{total_virtual}s 虚拟时间 @ {mips} MIPS）...")
    cmd = [os.path.join(RENODE_DIR, "renode.exe"),
           "--disable-xwt", "--console",
           "-e", f"include @{win_path(TMP_RESC)}"]
    timeout = 60 + total_virtual * 3   # 留足余量（100 MIPS 下 wall ≈ virtual）
    t0 = time.time()
    try:
        with open(LOG_PATH, "w", encoding="utf-8", errors="replace") as f:
            subprocess.run(cmd, cwd=RENODE_DIR, stdout=f, stderr=subprocess.STDOUT,
                           timeout=timeout)
    except subprocess.TimeoutExpired:
        print(f"[ERR] Renode 运行超时（>{timeout}s），看 {LOG_PATH}", file=sys.stderr)
        sys.exit(1)
    print(f"      完成，耗时 {time.time() - t0:.0f}s；日志: {LOG_PATH}")


def verify():
    """解析日志做关键里程碑检查，返回是否全部通过。"""
    with open(LOG_PATH, encoding="utf-8", errors="replace") as f:
        text = f.read()
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    has = lambda pat: any(re.search(pat, ln) for ln in lines)

    hb  = [ln for ln in lines if re.search(r"ctrl: hb ", ln)]
    pongs = [ln for ln in lines if ln == "PONG"]
    bad = [ln for ln in lines
           if re.search(r"ABI mismatch|app ABI mismatch|HardFault|bus fault|panic|assert", ln)]

    checks = [
        ("RTOS 启动",            has(r"jOS RTOS ready")),
        ("App 分区挂载",          has(r"RUST app mounted")),
        ("3 任务拉起",            has(r"spawned 3 tasks")),
        ("控制环心跳(hb)",        len(hb) >= 1),
        ("console 响应(PONG)",    len(pongs) >= 1),
        ("无 ABI/panic/fault",    len(bad) == 0),
    ]
    print("\n===== 验证摘要 =====")
    ok = True
    for name, passed in checks:
        print(f"  [{'PASS' if passed else 'FAIL'}] {name}")
        ok = ok and passed
    if hb:
        print(f"  控制环心跳 {len(hb)} 条: 首={hb[0]}")
        print(f"                      末={hb[-1]}")
    if bad:
        print("  异常行（前 5 条）:")
        for ln in bad[:5]:
            print("   ", ln)
    return ok


def main():
    ap = argparse.ArgumentParser(description="一键：编译 + Renode 运行 jOS RTOS + Rust App")
    ap.add_argument("--quick", action="store_true",
                    help="快速验证：构建后跑 ~27s 虚拟时间（保证抓到控制环心跳）")
    ap.add_argument("--seconds", type=int, default=None, metavar="N",
                    help="自定义运行秒数（发一次 console 命令后跑 N 秒）")
    ap.add_argument("--no-build", action="store_true",
                    help="跳过构建，直接用现有 app.bin")
    ap.add_argument("--keep-resc", action="store_true",
                    help="保留生成的临时 resc 文件")
    ap.add_argument("--mips", type=int, default=100, metavar="N",
                    help="Renode 仿真速度 MIPS（默认 100；时序保真用 168）")
    args = ap.parse_args()

    check_env()

    if args.no_build:
        if not os.path.exists(APP_BIN):
            print(f"[ERR] 缺 {APP_BIN}，先去掉 --no-build 构建一次", file=sys.stderr)
            sys.exit(1)
        print("[1/2] 跳过构建（--no-build）")
    else:
        build_app()

    full = not args.quick and args.seconds is None
    run_seconds = args.seconds if args.seconds is not None else 25
    mode = make_resc(args.mips, full, run_seconds)
    total = 62 if full else 2 + run_seconds
    print(f"      场景: {mode}（{'全量 62s' if full else f'{total}s 虚拟时间'}）")

    run_renode(args.mips, total)
    ok = verify()
    if not args.keep_resc and os.path.exists(TMP_RESC):
        os.remove(TMP_RESC)

    print("\n结果:", "PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
